default: &default
  adapter: postgresql
  encoding: utf-8
  database: reness
  pool: 5
  username: reness
  password: reness123

production:
  <<: *default

test:
  <<: *default
  database: reness_test

development:
  <<: *default


